# Generated by Django 4.2.6 on 2023-10-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('edu', models.CharField(max_length=100)),
                ('department_desc', models.TextField(null=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.department')),
            ],
        ),
    ]
